name: Go
on: [push, pull_request]
jobs:
  build:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: [ "1.15", "1.16", "1.17" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: checkout
        uses: actions/checkout@v2
      - name: build dot command
        run: go build -v cmd/dot/dot.go
      - name: test
        run: go test -race -v ./...
